### ISSUE TITLE
Allow use as library without `structopt` dependency

### ISSUE THREAD

**Issue by garthkerr** [wilsonzlin/hyperbuild#3]
Would it be possible to include as a crate without the binary dependency? Apologies, I'm slightly out of my depth here. In a prototype exercise to include minification with Zola (a rust-based static site generator), the inclusion of the binary raised some concern: https://github.com/getzola/zola/issues/542#issuecomment-646179801

**Comment by wilsonzlin** [comment]
I've extracted the CLI out to a separate package, so the library no longer has a binary or binary-specific dependencies.

There is a Rust RFC for supporting this without having to use a separate package (rust-lang/rfcs#2887), but it looks like it hasn't been approved yet.

Zola looks pretty cool! Let me know how it goes and if you run into any issues.

**Comment by garthkerr** [comment]
Fantastic! Thank you for implementing this so quickly. I've worked the update into my prototype.

**Comment by svenstaro** [comment]
Can't this be closed?

**Comment by garthkerr** [comment]
This was resolved in https://github.com/wilsonzlin/hyperbuild/commit/7a52bd7add644d9b604ba12abe7f97b643612ade
