### ISSUE TITLE
Inline SVG loses self-closing elements

### ISSUE THREAD

**Issue by kornelski** [wilsonzlin/hyperbuild#4]
In `<svg>` in HTML, the XML-ish self-closing syntax `<line/>` is valid and meaningful. Minified HTML mangles the `/>` in SVG by removing space before it, which changes nesting of elements and breaks SVG.

e.g. chart on:

https://lib.rs/crates/hyperbuild

does not survive minification.

`<line stroke-opacity=0.3 />` is changed to `<line stroke-opacity=0.3/>` which changes value of the attribute to `"0.3/"` instead of closing the element.

**Comment by wilsonzlin** [comment]
Great catch, thanks! I've fixed the issue and released to `0.1.8`.

Nice work on lib.rs BTW, looks very cool :smile:
